//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorsBook
    {
        public int AuthorId { get; set; }
        public string ISBN { get; set; }
        public System.DateTime YearPublished { get; set; }
        public int Edition { get; set; }
    }
}
