//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hi_Tech_Order_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public string PublisherId { get; set; }
        public string PublisherName { get; set; }
        public string WebAddress { get; set; }
    }
}
